
// Auto-generated by AutoPilot on 28-07-2023 at 20:30:56

const express = require('express');
const router = express.Router();
const nodemailer = require('nodemailer');

// Route to send an email
router.get('/replyEmail', (req, res) => {
    const { email } = req.query;

    // Creating a SMTP transporter
    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: 'example@gmail.com',
            pass: 'password'
        }
    });

    // Message object
    const message = {
        from: 'example@gmail.com',
        to: email,
        subject: 'Testing nodemailer',
        text: `Hi there, this is a testing email sent using nodemailer`
    };

    // Sending email
    transporter.sendMail(message, (err, info) => {
        if (err) {
            console.log('Error occurred. ' + err.message);
            res.sendStatus(500);
        } else {
            console.log('Message sent successfully!');
            res.sendStatus(200);
        }
    });
});

module.exports = router;